version: '3'
networks:
  influxdb:
services:
  influxdb:
    image: influxdb
    ports:
    - "18086:8086"
    - "18083:8083"
    volumes:
    - ${PWD}/influxdb/:/var/lib/influxdb:rw
    - ${PWD}/influxdb/:/etc/influxdb:rw
    - /etc/localtime:/etc/localtime
    environment:
    - INFLUXDB_GRAPHITE_ENABLED:true
    - INFLUXDB_DB:telegraf
    - INFLUXDB_ADMIN_ENABLED:true
    - INFLUXDB_ADMIN_USER:admin
    - INFLUXDB_ADMIN_PASSWORD:admin
    - INFLUXDB_USER:telegraf
    - INFLUXDB_USER_PASSWORD:telegraf
    networks:
    - influxdb
    restart: always
  chronograf:
    image: chronograf
    restart: always
    ports:
    - "18888:8888"
    networks:
    - influxdb
    depends_on:
    - influxdb
    volumes:
    - /etc/localtime:/etc/localtime
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 13000:3000
    depends_on:
    - influxdb
    - chronograf
    networks:
    - influxdb
    depends_on:
    - influxdb
    volumes:
    - ${PWD}/grafana/data:/var/lib/grafana:rw
    - ${PWD}/grafana/plugins:/var/lib/grafana/plugins:rw
    - /etc/localtime:/etc/localtime
networks:
  influxdb:
    driver: bridge
