db:
  restart: always
  image: postgres:latest   
  privileged: true  
  ports:
    - 5432:5432 
  environment:
    POSTGRES_PASSWORD: 123456 
    PGDATA: /var/lib/postgresql/data/pgdata 
  volumes:
    - /tmp/pg_data/data:/var/lib/postgresql/data/pgdata 
